version: '3'

services:
  php:
    image: php:7.2.20-cli
    volumes:
      - ./:/app
    working_dir: /app
    user: '1000:1000'
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t /app
